# -*- coding: utf-8 -*-
"""CEPython

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tmRUOyZC131zdt1s_qu2FRTt4FxmcixC
"""

import requests

def buscacep():
  #print('---------- CEPython ----------')
  cep = input("Qual o CEP? ")
  while len(cep) != 8:
    print('Errrouuuuu')
    cep = input("Qual o CEP? ")

  caixinha = requests.get('https://viacep.com.br/ws/{}/json/'.format(cep))
  endereço = caixinha.json()

  if 'erro' not in endereço:
    print("---- CEP ENCONTRADO ----")
    print('CEP: {}' .format(endereço['cep']))
    print('Cidade: {}' .format(endereço['localidade']))
    print('Estado: {}' .format(endereço['uf']))
  else:
    print('{} é um CEP invalido ou não foi encontrado.')


executar = True

while executar :
  print('---------- CEPython ----------')
  opcao = input('Escolha: \n[1]buscar um CEP \n[2]encerrar?')
  if opcao == '1':
    buscacep()
  else:
    executar = False